version: 2

jobs:


  macos:
    macos:
      xcode: "9.2"
    steps:
      - run: brew install mysql
      - run: brew services start mysql
      - run: sleep 3 && mysqladmin -uroot create test
      - checkout
      - run: swift build
      - run: echo "CREATE DATABASE vapor_test" | mysql -uroot
      # - run: swift build -c release
      - run: swift test

  linux:
    docker:
      - image: codevapor/swift:4.1
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: vapor_database
          # MYSQL_ROOT_HOST: %
          MYSQL_USER: vapor_username
          MYSQL_PASSWORD: vapor_password
    steps:
      - checkout
      - run: 
          name: Compile code
          command: swift build
      - run: 
          name: Run unit tests
          command: swift test
      - run: 
          name: Compile code with optimizations
          command: swift build -c release


  linux-fluent:
    docker:
      - image: codevapor/swift:4.1
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: vapor_database
          MYSQL_USER: vapor_username
          MYSQL_PASSWORD: vapor_password
    steps:
      - run:
          name: Clone Fluent MySQL
          command: git clone -b master https://github.com/vapor/fluent-mysql.git
          working_directory: ~/
      - run:
          name: Switch Fluent MySQL to this MySQL revision
          command: swift package edit MySQL --revision $CIRCLE_SHA1
          working_directory: ~/fluent-mysql
      - run:
          name: Run Fluent MySQL unit tests
          command: swift test
          working_directory: ~/fluent-mysql


workflows:
  version: 2
  tests:
    jobs:
     # - macos
      - linux
      - linux-fluent

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                
    jobs:
      - linux
      # - macos
